#!/bin/zsh

ZSH_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/oh-my-zsh"
[[ -d $ZSH_CACHE_DIR ]] || mkdir -p $ZSH_CACHE_DIR

# source antidote
source ${ZDOTDIR:-~}/.antidote/antidote.zsh


# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


# shortcut to this dotfiles path is $DOTFILES
export DOTFILES="$HOME/rc"

# your default editor
export EDITOR='vim'

# all of our zsh files
typeset -U config_files
config_files=($DOTFILES/zsh/*.zsh)
# load everything but the path and completion files
for file in ${config_files:#*/completion.zsh}; do
  source "$file"
done

# rehash if command not found (possibly recently installed)
zstyle ':completion:*' rehash true
# menu if nb items > 2
zstyle ':completion:*' menu select=2

ZSH_TAB_TITLE_CONCAT_FOLDER_PROCESS=true
ZSH_TAB_TITLE_DEFAULT_DISABLE_PREFIX=true

# use .localrc for SUPER SECRET CRAP that you don't
# want in your public, versioned repo.
[ -f ~/.localrc ] && . ~/.localrc

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Broot stuff
[ -f ~/Library/Preferences/org.dystroy.broot/launcher/bash/br ] && source ~/Library/Preferences/org.dystroy.broot/launcher/bash/br

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
#[[ ! -f ~/rc/zsh/p10k.zsh ]] || source ~/rc/zsh/p10k.zsh
if [ -e /Users/pyrho/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/pyrho/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
if [ -e /home/pyrho/.nix-profile/etc/profile.d/nix.sh ]; then . /home/pyrho/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

[ -f "/home/pyrho/.ghcup/env" ] && source ${HOME}/.config/broot/launcher/bash/br

[ -f "/home/pyrho/.ghcup/env" ] && source "/home/pyrho/.ghcup/env" # ghcup-env
# Generated for envman. Do not edit.
[ -s "$HOME/.config/envman/load.sh" ] && source "$HOME/.config/envman/load.sh"

# initialize plugins statically with ${ZDOTDIR:-~}/.zsh_plugins.txt
antidote load
export PATH="$VOLTA_HOME/bin:/opt/homebrew/opt/postgresql@17/bin:$PATH"

source /Users/pyrho/.config/broot/launcher/bash/br
